### ISSUE TITLE
Write output of process 3 to the description

### ISSUE THREAD

**Issue by jazarija** [bitcoinhodler/glacier-psbt#1]
Could we see in the current guideline what the exact output to process 3 is? Specifically the data (transaction?) that will later be used to feed on the quarantined laptop.

I guess I could figure it out from the input passed process 4, but I'd like to have a clear visual representation of what data gets later passed to the guaranteed HW.  It would help break down the flow of data passed around and think how this needs to be addressed securely.

**Comment by bitcoinhodler** [comment]
Done 8c4acf746722007381314376e1d1b327eb805af7
